### ISSUE TITLE
server returned 413 payload too large

### ISSUE THREAD

**Issue by PoiScript** [Hamuko/anifunnel#2]
hi, I tried to setup anifunnel in my home server but server only returned 413 errors when received request:

![image](https://github.com/Hamuko/anifunnel/assets/17513314/9eb56c0d-9458-41ac-815b-abcf7ac90034)

**Comment by Hamuko** [comment]
Never ran into this issue myself. Guessing that for some reason your Plex instance is returning webhook payloads that are >8KiB, which is the default size limit for strings in the web framework.

As a workaround, you could test increasing the data limit with an environment variable. For example `ROCKET_LIMITS="{string=131072}"` to set the maximum string size to 128KiB.

**Comment by PoiScript** [comment]
plex includes the thumbnail image in form data for some reason, which is causing the issue:

![image](https://github.com/Hamuko/anifunnel/assets/17513314/8fda8b33-0cca-455a-b39d-f913fc65d33e)

setting `ROCKET_LIMITS="{string=131072}"` fixes the problem, thanks!

**Comment by Hamuko** [comment]
Oh yeah, that seems to be a thing that Plex might do with its webhooks.

>As stated above, the payload is sent in JSON format inside a multipart HTTP POST request. For the `media.play` and `media.rate` events, a second part of the POST request contains a JPEG thumbnail for the media.

I think I need to adjust the default limits to get rid of this issue, since even if this doesn't apply to anifunnel's events (only `media.scrobble` are ever processed and it's unlikely they'd add a thumbnail to that), it's still confusing to see this in the logs.
