### ISSUE TITLE
Internal Server Error / Index out of bounds

### ISSUE THREAD

**Issue by GodOfOwls** [Hamuko/anifunnel#4]
Hi,

first of all thanks for your work. I've just deployed anifunnel in a docker and im getting an index out of bounds on the admin endpoint and all my scrobbles seem "not actionable".

Heres the Dockerlogs with RUST_BACKTRACE=1:
https://pastebin.com/wL8w6Dj4

And heres one with RUST_BACKTRACE=full:
https://pastebin.com/qVqtdF79

My Docker Command is as follows:

`docker run \
    -p 8000:8000 \
	-e "ANILIST_PLEX_USER=jonasheinz" \
    -e "ANILIST_TOKEN="real_token_here" \
    ghcr.io/hamuko/anifunnel:latest`

Thanks again for the Work and if you need any more info just lemme know.

**Comment by Hamuko** [comment]
Looks like the management interface will crash if you don't have any anime in your watching list. Should be fixed to `master` now.

As for the non-actionable events, they occur whenever Plex sends Anifunnel a webhook that isn't a scrobble event for an episode in the first season of a show (or any season > 0 if multi-season mode is on). It's completely normal to have your logs full of them since most of the webhook events that Anifunnel receives are non-actionable.

**Comment by GodOfOwls** [comment]
Thanks for the quick reply. After some more testing today it also seems to happen on Scrobble Post events and not just the admin event. 
https://pastebin.com/tj4ScCmy

Ill try out Master right away and let you know if it fixed it.

**Comment by GodOfOwls** [comment]
The Update fixed it.

Also im an idiot. I didn't RTFM correctly and wasn't aware i had to add animes to my Watching List before anifunnel would mark them as watched. For some reason i was under the Assumption it also adds it if it doesn't exist.
