### ISSUE TITLE
support for shows not only on currently watching list?

### ISSUE THREAD

**Issue by Badtz13** [Hamuko/anifunnel#7]
Correct me if I am wrong, but it seems that this will only update your anilist if the show is in the user's currently watching list. It would be really cool if there was an option you could enable to either search the entire site, or search the user's other lists (planning, completed, rewatching, etc.)

It's pretty common that people will want to rewatch a show, and it won't be on their watching list, so it would be really great if this could do that automatically.

**Comment by Hamuko** [comment]
> Correct me if I am wrong, but it seems that this will only update your anilist if the show is in the user's currently watching list.

Correct. It is quite explicitly in the README: _“The updating logic is rather conservative: the anime must be found within your watching list, and must have a matching episode count.”_

> It would be really cool if there was an option you could enable to either search the entire site, or search the user's other lists (planning, completed, rewatching, etc.)

Including the rewatch list makes sense since it’s basically just an extension of the watch list and should be a relatively easy change. I think I’ll do it at some point.

As for the other lists, they have all kinds of problems. The fuzzy matching works better the less results there are and my watching list only ever contains about 20 titles at a time. Meanwhile my planning and completed lists are measured in the hundreds or thousands respectively. The amount of naming differences between services would also mean that you could never really trust anifunnel to properly match the show.

If someone wanted to contribute a feature that would optionally also attempt to get a match from the planning list, or possibly by searching the entire site, I’d be willing to merge it. Personally, I don’t really have a need for it and I don’t have the energy to figure out how to get it work even relatively reliably.

**Comment by Hamuko** [comment]
Master branch should now have support for updating the rewatching list too. Well, theoretically at least, since I'm not rewatching anything at the moment and I don't wanna set up anything for testing.
